### ISSUE TITLE
Instafeed alternative

### ISSUE THREAD

**Issue by darcemac** [jhvanderschee/jekyllcodex#12]
Hi, I wasn't sure how best to contact you.

My question is in relation to your Instafeed alternative. I set up a zap by following your steps and adding the following settings;
    Feed Title: {username}
    Max Records: 5
    Item Title: Caption: {caption text}
    Source URL: {link}
    Content: Tags: {tags}
    Media URL: {images standard resolution url}
    Media MIME Type: image/jpeg

I can pull in the feed with the js code you provided but all that shows are empty a tags, for example <img src="&#123;images standard&nbsp;resolution&#125;">

It's like it can't parse what was added via Zap. I'm probably doing something completely wrong...

**Comment by jhvanderschee** [comment]
The brackets need to be Zapier variables in your Zap. Currently they are not. Hope it helps!

**Comment by jhvanderschee** [comment]
Please use https://profilepageimages.usecue.com/.
