### ISSUE TITLE
Need Jekyll Page view counter

### ISSUE THREAD

**Issue by ElectricRCAircraftGuy** [jhvanderschee/jekyllcodex#14]
First off, **thank you** for making your Jekyllcodex website! It's helped me a lot, and your [GitHub issue-based comments](https://jekyllcodex.org/blog/gdpr-compliant-comment/) are ingenious and exactly what I needed and was hoping for in comments!

----

Now, for this issue:

I'd like a way to track unique user page visits to my site. Any idea how to do this? Maybe you can come up with a solution and write about it here? https://jekyllcodex.org/without-plugins/

---------

Possible tracks to get you started:

1. https://github.com/brentvollebregt/hit-counter
1. https://hitcounter.pythonanywhere.com/
1. https://hits.dwyl.com/
1. https://stackoverflow.com/questions/57747640/how-to-implement-a-basic-page-view-counter-for-a-github-pages-powered-site
1. Javascript to talk to some GitHub REST API (whatever this means) to store a variable on GitHub?
1. https://stackoverflow.com/questions/10970113/google-analytics-simple-visitors-count

Ideally it would rely on only mainstream, reputable servers so we don't have to worry about some side-project server going offline someday.

Ideally it would be no cost, but if it costs like $2/month (which is what I pay per month for [100 GB of Google cloud storage](https://one.google.com/about), for instance) that'd be fine too.

**Comment by jhvanderschee** [comment]
Easy... just [count the hits on the server](https://forums.cpanel.net/threads/alternative-to-awstats.65596/#post-304011). No cost and little to no privacy concerns. This has been wildly successful [since the year 2000](https://en.wikipedia.org/wiki/AWStats)! I know... I am a 'dev dinosaur', as [Chris Ferdinandy](https://leanweb.dev/) would say, but I am proud of it.

**Comment by ElectricRCAircraftGuy** [comment]
How do I "just [count the hits on the server](https://forums.cpanel.net/threads/alternative-to-awstats.65596/#post-304011)"? This link doesn't seem to say anything about that. 

If it does, I don't understand. I am hoping to see a detailed demo.

**Comment by jhvanderschee** [comment]
If your host has it set up, cPanel includes webalizer and analog. In addition, there are several others (paid/unpaid) that you can review as well. Letting your Jekyll website count your visitors is ill adviced.

**Comment by ElectricRCAircraftGuy** [comment]
My host is GitHub. My Jekyll site is hosted by [GitHub Pages](https://pages.github.com/).

**Comment by jhvanderschee** [comment]
You can use somthing like this https://hits.sh/.
