### ISSUE TITLE
webshop send form by php

### ISSUE THREAD

**Issue by gitlerat** [jhvanderschee/jekyllcodex#15]
Hi, I recreated my own site with your webshop implementation. The site is hosted on my webspace and the server is capable of php. I tried that the checkout form will be send over classic php to my mail. 
I failed at trying to implement it. Could you give me a hint how your code has to be changed in order to send the mail this way?

**Comment by gitlerat** [comment]
If above is to much to ask, I would be happy if you could point out how your checkout form is being sent per mail :)

**Comment by jhvanderschee** [comment]
https://github.com/jhvanderschee/jekyllcodex/blob/gh-pages/_includes/checkout.html line 14... there you see how the form is handled.
