### ISSUE TITLE
Missing Some CSS Classes

### ISSUE THREAD

**Issue by manunamz** [jhvanderschee/jekyllcodex#16]
[cookie-consent.html](https://raw.githubusercontent.com/jhvanderschee/jekyllcodex/gh-pages/_includes/cookie-consent.html) (and some others, I think) uses some css classes that are not included in the html include itself -- they look like they assume Bootstrap is installed?:

- `class="btn btn-primary btn-sm"`
- `class="btn btn-primary btn-sm"`

```html
<div id="cookie-notice">
  <span>We would like to use third party cookies and scripts to improve the functionality of this website.</span>
  <a id="cookie-notice-accept" class="btn btn-primary btn-sm">Approve</a>  <!-- here -->
  <a href="/privacy" class="btn btn-primary btn-sm">More info</a> <!-- and here -->
</div>
```

**Comment by jhvanderschee** [comment]
I deliberately left them out. You can look at the example code to find the appropriate styles.
