### ISSUE TITLE
Plugin-free solution for modal window

### ISSUE THREAD

**Issue by keunes** [jhvanderschee/jekyllcodex#18]
Beste @jhvanderschee,
For AntennaPod (podcast app for Android) I would like to introduce a modal window on our website to inform visitors that we really prefer non-monetary contributions, when they click on the 'donate' link: https://github.com/AntennaPod/antennapod.github.io/issues/122

Someone built the site for our open source project, and I do low-level maintenance & improvements. But I guess it'd involve JS and that's not something I can provide. Searching for 'modal window' solutions for Jekyll, I ended up on your website. Now I'm wondering: would you be willing to you be willing to prepare a plugin-free solution for modal windows & tailor it a bit to our need? Ik doe graag een donatie op persoonlijke titel.

M.v.g.

**Comment by jhvanderschee** [comment]
No problem. You can find it here: https://jekyllcodex.org/without-plugin/button-modal/. Let me know if that works for you.
