### ISSUE TITLE
Pagination for image gallery

### ISSUE THREAD

**Issue by SabeBarker** [jhvanderschee/jekyllcodex#5]
Hello,

First off I would like to thank you for your site. Without-plugins is awesome. Being new to jekyll it has also helped me to understand more about how things work.

With your [image-gallery](https://github.com/jhvanderschee/jekyllcodex/blob/gh-pages/_without-plugin/image-gallery.md) I was wondering whether it is possible to paginate? 

Your response is greatly appreciated.

**Comment by jhvanderschee** [comment]
You are welcome! It is not possible in the current code. Why would you want to paginate? It would be javascript pagination. Is that really desired? Does native lazy-loading solve this problem perhaps?
