### ISSUE TITLE
License? 

### ISSUE THREAD

**Issue by luispuerto** [jhvanderschee/jekyllcodex#7]
Hey! 

It would be great if you add a license to your work… 

https://choosealicense.com/no-permission/

MIT? https://choosealicense.com/licenses/mit/#suggest-this-license

**Comment by jhvanderschee** [comment]
At jekyllcodex.org you can read:

Copyright. Feel free to use all code presented on this website. The code of the website itself may also be used, as this website is a demo of the code it presents. However, respect the copyright of the used trademarks and the licenses of the open-source software used, as their rights belong to their respective owners. All images are CC0 images from Unsplash.

Liquid, jQuery, Bootstrap, Google Analytics, Bootswatch, Forestry, Github, Netlify (CMS), CloudCannon, Mollie API, Markdown, Jekyll... they all have licenses. I just combined/used them in a VERY basic, unoriginal and 'as intended' way. This is not software creation. This is a demo, using licensed software. Should I (re-)license that? What would that even mean? That seems more confusing than helpful to me.

**Comment by luispuerto** [comment]
Whatever new you have created deserve a license compatible with the other software you are using as support. At least legally speaking. Of course you can do whatever you want. But no license, means copyright, even stating what you are stating in the site. 

You should use a license for your code —even if it's just one line or unoriginal— and a license for your content —since licenses for code usually aren't suitable for code an viceversa. 

As you see most of the pieces of software you are using as support are using MIT, that is a really permissive license and compatible with most of further uses. You can also go with a creative commons for your content and that's it. 

I know that it looks like a very stupid think but strictly legally speaking is like that. 

https://opensource.guide/legal/

**Comment by luispuerto** [comment]
PS/ I don't think you need to add the licenses of Markdown, or Jekyll, or Forestry, or… whatever you are not strictly including in your repo. 

This is more or less a good example https://github.com/mmistakes/minimal-mistakes#license

**Comment by jhvanderschee** [comment]
I am not going to list all licensed code in this project. That is simply too much (work) and keeps changing. I can say that all code I created MYSELF is MIT licensed, but it might give people a false sense of security, as it might not be clear to everyone which code falls under which license.

However, if you think it is a good idea and helpful, I will add such a license. :-)

**Comment by luispuerto** [comment]
I think that it's a good idea to state the license. 

PS1/ and it's going to take you one minute. 
PS2/ I think everyone understands that when you are add a license to your project and you are including other pieces of software that are not yours, you are only stating the license for your part. Anyhow, if you choose MIT I think that's it because all the other bits and pieces are MIT too.

**Comment by jhvanderschee** [comment]
I have added the license to the README
